In [2]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [76]:
train_df = pd.read_csv("train.csv")
train_df = train_df.dropna(axis="columns", how="all")
train_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [77]:
train_df.drop(["Cabin", "Ticket", "Name", "PassengerId"], axis=1, inplace=True)
train_df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [78]:
boolean_df = train_df.isna()

for i in range(boolean_df.index.size):
    for j in range(8):
        if(boolean_df.iloc[i, j]):
            print("row: {} column: {}".format(i, boolean_df.columns[j]))

row: 5 column: Age
row: 17 column: Age
row: 19 column: Age
row: 26 column: Age
row: 28 column: Age
row: 29 column: Age
row: 31 column: Age
row: 32 column: Age
row: 36 column: Age
row: 42 column: Age
row: 45 column: Age
row: 46 column: Age
row: 47 column: Age
row: 48 column: Age
row: 55 column: Age
row: 61 column: Embarked
row: 64 column: Age
row: 65 column: Age
row: 76 column: Age
row: 77 column: Age
row: 82 column: Age
row: 87 column: Age
row: 95 column: Age
row: 101 column: Age
row: 107 column: Age
row: 109 column: Age
row: 121 column: Age
row: 126 column: Age
row: 128 column: Age
row: 140 column: Age
row: 154 column: Age
row: 158 column: Age
row: 159 column: Age
row: 166 column: Age
row: 168 column: Age
row: 176 column: Age
row: 180 column: Age
row: 181 column: Age
row: 185 column: Age
row: 186 column: Age
row: 196 column: Age
row: 198 column: Age
row: 201 column: Age
row: 214 column: Age
row: 223 column: Age
row: 229 column: Age
row: 235 column: Age
row: 240 column: Age
row: 241 column: Age
row: 250 column: Age
row: 256 column: Age
row: 260 column: Age
row: 264 column: Age
row: 270 column: Age
row: 274 column: Age
row: 277 column: Age
row: 284 column: Age
row: 295 column: Age
row: 298 column: Age
row: 300 column: Age
row: 301 column: Age
row: 303 column: Age
row: 304 column: Age
row: 306 column: Age
row: 324 column: Age
row: 330 column: Age
row: 334 column: Age
row: 335 column: Age
row: 347 column: Age
row: 351 column: Age
row: 354 column: Age
row: 358 column: Age
row: 359 column: Age
row: 364 column: Age
row: 367 column: Age
row: 368 column: Age
row: 375 column: Age
row: 384 column: Age
row: 388 column: Age
row: 409 column: Age
row: 410 column: Age
row: 411 column: Age
row: 413 column: Age
row: 415 column: Age
row: 420 column: Age
row: 425 column: Age
row: 428 column: Age
row: 431 column: Age
row: 444 column: Age
row: 451 column: Age
row: 454 column: Age
row: 457 column: Age
row: 459 column: Age
row: 464 column: Age
row: 466 column: Age
row: 468 column: Age
row: 470 column: Age
row: 475 column: Age
row: 481 column: Age
row: 485 column: Age
row: 490 column: Age
row: 495 column: Age
row: 497 column: Age
row: 502 column: Age
row: 507 column: Age
row: 511 column: Age
row: 517 column: Age
row: 522 column: Age
row: 524 column: Age
row: 527 column: Age
row: 531 column: Age
row: 533 column: Age
row: 538 column: Age
row: 547 column: Age
row: 552 column: Age
row: 557 column: Age
row: 560 column: Age
row: 563 column: Age
row: 564 column: Age
row: 568 column: Age
row: 573 column: Age
row: 578 column: Age
row: 584 column: Age
row: 589 column: Age
row: 593 column: Age
row: 596 column: Age
row: 598 column: Age
row: 601 column: Age
row: 602 column: Age
row: 611 column: Age
row: 612 column: Age
row: 613 column: Age
row: 629 column: Age
row: 633 column: Age
row: 639 column: Age
row: 643 column: Age
row: 648 column: Age
row: 650 column: Age
row: 653 column: Age
row: 656 column: Age
row: 667 column: Age
row: 669 column: Age
row: 674 column: Age
row: 680 column: Age
row: 692 column: Age
row: 697 column: Age
row: 709 column: Age
row: 711 column: Age
row: 718 column: Age
row: 727 column: Age
row: 732 column: Age
row: 738 column: Age
row: 739 column: Age
row: 740 column: Age
row: 760 column: Age
row: 766 column: Age
row: 768 column: Age
row: 773 column: Age
row: 776 column: Age
row: 778 column: Age
row: 783 column: Age
row: 790 column: Age
row: 792 column: Age
row: 793 column: Age
row: 815 column: Age
row: 825 column: Age
row: 826 column: Age
row: 828 column: Age
row: 829 column: Embarked
row: 832 column: Age
row: 837 column: Age
row: 839 column: Age
row: 846 column: Age
row: 849 column: Age
row: 859 column: Age
row: 863 column: Age
row: 868 column: Age
row: 878 column: Age
row: 888 column: Age

In [79]:
# ignore Age and Embarked for now - set later based on Name, ticket price, etc.
# ignore Embarked as well! Need to make multiple columns for the three values
train_df.drop(["Fare", "Age", "Embarked"], axis=1, inplace=True)

# train_df = train_df.dropna()
train_df

     Survived  Pclass     Sex  SibSp  Parch
0           0       3    male      1      0
1           1       1  female      1      0
2           1       3  female      0      0
3           1       1  female      1      0
4           0       3    male      0      0
..        ...     ...     ...    ...    ...
886         0       2    male      0      0
887         1       1  female      0      0
888         0       3  female      1      2
889         1       1    male      0      0
890         0       3    male      0      0

[891 rows x 5 columns]

In [80]:
# convert non-numeric data to numbers
train_df["Sex"] = train_df["Sex"].apply(lambda x: 0 if(x=="male") else 1)
train_df

     Survived  Pclass  Sex  SibSp  Parch
0           0       3    0      1      0
1           1       1    1      1      0
2           1       3    1      0      0
3           1       1    1      1      0
4           0       3    0      0      0
..        ...     ...  ...    ...    ...
886         0       2    0      0      0
887         1       1    1      0      0
888         0       3    1      1      2
889         1       1    0      0      0
890         0       3    0      0      0

[891 rows x 5 columns]

In [81]:

train_df["Survived"].value_counts()

0    549
1    342
Name: Survived, dtype: int64

## Create a Train/Test Split

In [99]:
selected_features = train_df[["Pclass", "Sex", "SibSp", "Parch"]]
y = train_df["Survived"]
y.array

<PandasArray>
[0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
 ...
 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]
Length: 891, dtype: int64

In [86]:
from sklearn.model_selection import train_test_split

X = selected_features

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=42)

In [92]:
X_train.head()

     Pclass  Sex  SibSp  Parch
331       1    0      0      0
733       2    0      0      0
382       3    0      0      0
704       3    0      1      0
813       3    1      4      2

In [100]:
y_train

     Survived
331         0
733         0
382         0
704         0
813         0
..        ...
106         1
270         0
860         0
435         1
102         0

[712 rows x 1 columns]

## Pre-processing (Normalize data)

In [93]:
# Scale your data

#setup MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

#set initial sizing of minmaxscaler using training data
X_scaler = MinMaxScaler().fit(X_train)

In [94]:
#use MinMaxScaler to transform the data in the training and test data sets
#so that it is not weighted improperly

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Train the Model

In [95]:
classifier = LogisticRegression()
classifier

LogisticRegression()

In [102]:
#create the model using the training data!
classifier.fit(X_train_scaled, y_train["Survived"].array)

LogisticRegression()

## Hyperparameter Tuning

In [117]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV

param_grid = {'C': [1, 5, 10, 50, 100, 200, 500],
              'max_iter': [100, 200, 300],
              'tol': [.0001, 0.001, 0.005]}

grid = GridSearchCV(classifier, param_grid, verbose=3)

In [118]:
# Train the model with GridSearch
grid.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 63 candidates, totalling 315 fits
[CV] C=1, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=100, tol=0.0001, score=0.811, total=   0.0s
[CV] C=1, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=100, tol=0.0001, score=0.804, total=   0.0s
[CV] C=1, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=100, tol=0.0001, score=0.768, total=   0.0s
[CV] C=1, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=100, tol=0.0001, score=0.754, total=   0.0s
[CV] C=1, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=100, tol=0.0001, score=0.831, total=   0.0s
[CV] C=1, max_iter=100, tol=0.001 ....................................
[CV] ........ C=1, max_iter=100, tol=0.001, score=0.811, total=   0.0s
[CV] C=1, max_iter=100, tol=0.001 ....................................
[CV] ........ C=1, max_iter=100, tol=0.001, score=0.804, total=   0.0s
[CV] C=1, max_iter=100, tol=0.001 ....................................
[CV] ........ C=1, max_iter=100, tol=0.001, score=0.768, total=   0.0s
[CV] C=1, max_iter=100, tol=0.001 ....................................
[CV] ........ C=1, max_iter=100, tol=0.001, score=0.754, total=   0.0s
[CV] C=1, max_iter=100, tol=0.001 ....................................
[CV] ........ C=1, max_iter=100, tol=0.001, score=0.831, total=   0.0s
[CV] C=1, max_iter=100, tol=0.005 ....................................
[CV] ........ C=1, max_iter=100, tol=0.005, score=0.811, total=   0.0s
[CV] C=1, max_iter=100, tol=0.005 ....................................
[CV] ........ C=1, max_iter=100, tol=0.005, score=0.804, total=   0.0s
[CV] C=1, max_iter=100, tol=0.005 ....................................
[CV] ........ C=1, max_iter=100, tol=0.005, score=0.768, total=   0.0s
[CV] C=1, max_iter=100, tol=0.005 ....................................
[CV] ........ C=1, max_iter=100, tol=0.005, score=0.754, total=   0.0s
[CV] C=1, max_iter=100, tol=0.005 ....................................
[CV] ........ C=1, max_iter=100, tol=0.005, score=0.831, total=   0.0s
[CV] C=1, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=200, tol=0.0001, score=0.811, total=   0.0s
[CV] C=1, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=200, tol=0.0001, score=0.804, total=   0.0s
[CV] C=1, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=200, tol=0.0001, score=0.768, total=   0.0s
[CV] C=1, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=200, tol=0.0001, score=0.754, total=   0.0s
[CV] C=1, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=200, tol=0.0001, score=0.831, total=   0.0s
[CV] C=1, max_iter=200, tol=0.001 ....................................
[CV] ........ C=1, max_iter=200, tol=0.001, score=0.811, total=   0.0s
[CV] C=1, max_iter=200, tol=0.001 ....................................
[CV] ........ C=1, max_iter=200, tol=0.001, score=0.804, total=   0.0s
[CV] C=1, max_iter=200, tol=0.001 ....................................
[CV] ........ C=1, max_iter=200, tol=0.001, score=0.768, total=   0.0s
[CV] C=1, max_iter=200, tol=0.001 ....................................
[CV] ........ C=1, max_iter=200, tol=0.001, score=0.754, total=   0.0s
[CV] C=1, max_iter=200, tol=0.001 ....................................
[CV] ........ C=1, max_iter=200, tol=0.001, score=0.831, total=   0.0s
[CV] C=1, max_iter=200, tol=0.005 ....................................
[CV] ........ C=1, max_iter=200, tol=0.005, score=0.811, total=   0.0s
[CV] C=1, max_iter=200, tol=0.005 ....................................
[CV] ........ C=1, max_iter=200, tol=0.005, score=0.804, total=   0.0s
[CV] C=1, max_iter=200, tol=0.005 ....................................
[CV] ........ C=1, max_iter=200, tol=0.005, score=0.768, total=   0.0s
[CV] C=1, max_iter=200, tol=0.005 ....................................
[CV] ........ C=1, max_iter=200, tol=0.005, score=0.754, total=   0.0s
[CV] C=1, max_iter=200, tol=0.005 ....................................
[CV] ........ C=1, max_iter=200, tol=0.005, score=0.831, total=   0.0s
[CV] C=1, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=300, tol=0.0001, score=0.811, total=   0.0s
[CV] C=1, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=300, tol=0.0001, score=0.804, total=   0.0s
[CV] C=1, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=300, tol=0.0001, score=0.768, total=   0.0s
[CV] C=1, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=300, tol=0.0001, score=0.754, total=   0.0s
[CV] C=1, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=1, max_iter=300, tol=0.0001, score=0.831, total=   0.0s
[CV] C=1, max_iter=300, tol=0.001 ....................................
[CV] ........ C=1, max_iter=300, tol=0.001, score=0.811, total=   0.0s
[CV] C=1, max_iter=300, tol=0.001 ....................................

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

[CV] ........ C=1, max_iter=300, tol=0.001, score=0.804, total=   0.0s
[CV] C=1, max_iter=300, tol=0.001 ....................................
[CV] ........ C=1, max_iter=300, tol=0.001, score=0.768, total=   0.0s
[CV] C=1, max_iter=300, tol=0.001 ....................................
[CV] ........ C=1, max_iter=300, tol=0.001, score=0.754, total=   0.0s
[CV] C=1, max_iter=300, tol=0.001 ....................................
[CV] ........ C=1, max_iter=300, tol=0.001, score=0.831, total=   0.0s
[CV] C=1, max_iter=300, tol=0.005 ....................................
[CV] ........ C=1, max_iter=300, tol=0.005, score=0.811, total=   0.0s
[CV] C=1, max_iter=300, tol=0.005 ....................................
[CV] ........ C=1, max_iter=300, tol=0.005, score=0.804, total=   0.0s
[CV] C=1, max_iter=300, tol=0.005 ....................................
[CV] ........ C=1, max_iter=300, tol=0.005, score=0.768, total=   0.0s
[CV] C=1, max_iter=300, tol=0.005 ....................................
[CV] ........ C=1, max_iter=300, tol=0.005, score=0.754, total=   0.0s
[CV] C=1, max_iter=300, tol=0.005 ....................................
[CV] ........ C=1, max_iter=300, tol=0.005, score=0.831, total=   0.0s
[CV] C=5, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=100, tol=0.0001, score=0.811, total=   0.0s
[CV] C=5, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=100, tol=0.0001, score=0.804, total=   0.0s
[CV] C=5, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=100, tol=0.0001, score=0.768, total=   0.0s
[CV] C=5, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=100, tol=0.0001, score=0.768, total=   0.0s
[CV] C=5, max_iter=100, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=100, tol=0.0001, score=0.831, total=   0.0s
[CV] C=5, max_iter=100, tol=0.001 ....................................
[CV] ........ C=5, max_iter=100, tol=0.001, score=0.811, total=   0.0s
[CV] C=5, max_iter=100, tol=0.001 ....................................
[CV] ........ C=5, max_iter=100, tol=0.001, score=0.804, total=   0.0s
[CV] C=5, max_iter=100, tol=0.001 ....................................
[CV] ........ C=5, max_iter=100, tol=0.001, score=0.768, total=   0.0s
[CV] C=5, max_iter=100, tol=0.001 ....................................
[CV] ........ C=5, max_iter=100, tol=0.001, score=0.768, total=   0.0s
[CV] C=5, max_iter=100, tol=0.001 ....................................
[CV] ........ C=5, max_iter=100, tol=0.001, score=0.831, total=   0.0s
[CV] C=5, max_iter=100, tol=0.005 ....................................
[CV] ........ C=5, max_iter=100, tol=0.005, score=0.811, total=   0.0s
[CV] C=5, max_iter=100, tol=0.005 ....................................
[CV] ........ C=5, max_iter=100, tol=0.005, score=0.804, total=   0.0s
[CV] C=5, max_iter=100, tol=0.005 ....................................
[CV] ........ C=5, max_iter=100, tol=0.005, score=0.768, total=   0.0s
[CV] C=5, max_iter=100, tol=0.005 ....................................
[CV] ........ C=5, max_iter=100, tol=0.005, score=0.768, total=   0.0s
[CV] C=5, max_iter=100, tol=0.005 ....................................
[CV] ........ C=5, max_iter=100, tol=0.005, score=0.831, total=   0.0s
[CV] C=5, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=200, tol=0.0001, score=0.811, total=   0.0s
[CV] C=5, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=200, tol=0.0001, score=0.804, total=   0.0s
[CV] C=5, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=200, tol=0.0001, score=0.768, total=   0.0s
[CV] C=5, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=200, tol=0.0001, score=0.768, total=   0.0s
[CV] C=5, max_iter=200, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=200, tol=0.0001, score=0.831, total=   0.0s
[CV] C=5, max_iter=200, tol=0.001 ....................................
[CV] ........ C=5, max_iter=200, tol=0.001, score=0.811, total=   0.0s
[CV] C=5, max_iter=200, tol=0.001 ....................................
[CV] ........ C=5, max_iter=200, tol=0.001, score=0.804, total=   0.0s
[CV] C=5, max_iter=200, tol=0.001 ....................................
[CV] ........ C=5, max_iter=200, tol=0.001, score=0.768, total=   0.0s
[CV] C=5, max_iter=200, tol=0.001 ....................................
[CV] ........ C=5, max_iter=200, tol=0.001, score=0.768, total=   0.0s
[CV] C=5, max_iter=200, tol=0.001 ....................................
[CV] ........ C=5, max_iter=200, tol=0.001, score=0.831, total=   0.0s
[CV] C=5, max_iter=200, tol=0.005 ....................................
[CV] ........ C=5, max_iter=200, tol=0.005, score=0.811, total=   0.0s
[CV] C=5, max_iter=200, tol=0.005 ....................................
[CV] ........ C=5, max_iter=200, tol=0.005, score=0.804, total=   0.0s
[CV] C=5, max_iter=200, tol=0.005 ....................................
[CV] ........ C=5, max_iter=200, tol=0.005, score=0.768, total=   0.0s
[CV] C=5, max_iter=200, tol=0.005 ....................................
[CV] ........ C=5, max_iter=200, tol=0.005, score=0.768, total=   0.0s
[CV] C=5, max_iter=200, tol=0.005 ....................................
[CV] ........ C=5, max_iter=200, tol=0.005, score=0.831, total=   0.0s
[CV] C=5, max_iter=300, tol=0.0001 ...................................

C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

[CV] ....... C=5, max_iter=300, tol=0.0001, score=0.811, total=   0.0s
[CV] C=5, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=300, tol=0.0001, score=0.804, total=   0.0s
[CV] C=5, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=300, tol=0.0001, score=0.768, total=   0.0s
[CV] C=5, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=300, tol=0.0001, score=0.768, total=   0.0s
[CV] C=5, max_iter=300, tol=0.0001 ...................................
[CV] ....... C=5, max_iter=300, tol=0.0001, score=0.831, total=   0.0s
[CV] C=5, max_iter=300, tol=0.001 ....................................
[CV] ........ C=5, max_iter=300, tol=0.001, score=0.811, total=   0.0s
[CV] C=5, max_iter=300, tol=0.001 ....................................
[CV] ........ C=5, max_iter=300, tol=0.001, score=0.804, total=   0.0s
[CV] C=5, max_iter=300, tol=0.001 ....................................
[CV] ........ C=5, max_iter=300, tol=0.001, score=0.768, total=   0.0s
[CV] C=5, max_iter=300, tol=0.001 ....................................
[CV] ........ C=5, max_iter=300, tol=0.001, score=0.768, total=   0.0s
[CV] C=5, max_iter=300, tol=0.001 ....................................
[CV] ........ C=5, max_iter=300, tol=0.001, score=0.831, total=   0.0s
[CV] C=5, max_iter=300, tol=0.005 ....................................
[CV] ........ C=5, max_iter=300, tol=0.005, score=0.811, total=   0.0s
[CV] C=5, max_iter=300, tol=0.005 ....................................
[CV] ........ C=5, max_iter=300, tol=0.005, score=0.804, total=   0.0s
[CV] C=5, max_iter=300, tol=0.005 ....................................
[CV] ........ C=5, max_iter=300, tol=0.005, score=0.768, total=   0.0s
[CV] C=5, max_iter=300, tol=0.005 ....................................
[CV] ........ C=5, max_iter=300, tol=0.005, score=0.768, total=   0.0s
[CV] C=5, max_iter=300, tol=0.005 ....................................
[CV] ........ C=5, max_iter=300, tol=0.005, score=0.831, total=   0.0s
[CV] C=10, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=100, tol=0.0001, score=0.825, total=   0.0s
[CV] C=10, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=100, tol=0.0001, score=0.804, total=   0.0s
[CV] C=10, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=100, tol=0.0001, score=0.775, total=   0.0s
[CV] C=10, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=100, tol=0.0001, score=0.768, total=   0.0s
[CV] C=10, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=100, tol=0.0001, score=0.831, total=   0.0s
[CV] C=10, max_iter=100, tol=0.001 ...................................
[CV] ....... C=10, max_iter=100, tol=0.001, score=0.825, total=   0.0s
[CV] C=10, max_iter=100, tol=0.001 ...................................
[CV] ....... C=10, max_iter=100, tol=0.001, score=0.804, total=   0.0s
[CV] C=10, max_iter=100, tol=0.001 ...................................
[CV] ....... C=10, max_iter=100, tol=0.001, score=0.775, total=   0.0s
[CV] C=10, max_iter=100, tol=0.001 ...................................
[CV] ....... C=10, max_iter=100, tol=0.001, score=0.768, total=   0.0s
[CV] C=10, max_iter=100, tol=0.001 ...................................
[CV] ....... C=10, max_iter=100, tol=0.001, score=0.831, total=   0.0s
[CV] C=10, max_iter=100, tol=0.005 ...................................
[CV] ....... C=10, max_iter=100, tol=0.005, score=0.825, total=   0.0s
[CV] C=10, max_iter=100, tol=0.005 ...................................
[CV] ....... C=10, max_iter=100, tol=0.005, score=0.804, total=   0.0s
[CV] C=10, max_iter=100, tol=0.005 ...................................
[CV] ....... C=10, max_iter=100, tol=0.005, score=0.775, total=   0.0s
[CV] C=10, max_iter=100, tol=0.005 ...................................
[CV] ....... C=10, max_iter=100, tol=0.005, score=0.768, total=   0.0s
[CV] C=10, max_iter=100, tol=0.005 ...................................
[CV] ....... C=10, max_iter=100, tol=0.005, score=0.831, total=   0.0s
[CV] C=10, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=200, tol=0.0001, score=0.825, total=   0.0s
[CV] C=10, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=200, tol=0.0001, score=0.804, total=   0.0s
[CV] C=10, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=200, tol=0.0001, score=0.775, total=   0.0s
[CV] C=10, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=200, tol=0.0001, score=0.768, total=   0.0s
[CV] C=10, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=200, tol=0.0001, score=0.831, total=   0.0s
[CV] C=10, max_iter=200, tol=0.001 ...................................
[CV] ....... C=10, max_iter=200, tol=0.001, score=0.825, total=   0.0s
[CV] C=10, max_iter=200, tol=0.001 ...................................
[CV] ....... C=10, max_iter=200, tol=0.001, score=0.804, total=   0.0s
[CV] C=10, max_iter=200, tol=0.001 ...................................
[CV] ....... C=10, max_iter=200, tol=0.001, score=0.775, total=   0.0s
[CV] C=10, max_iter=200, tol=0.001 ...................................
[CV] ....... C=10, max_iter=200, tol=0.001, score=0.768, total=   0.0s
[CV] C=10, max_iter=200, tol=0.001 ...................................
[CV] ....... C=10, max_iter=200, tol=0.001, score=0.831, total=   0.0s
[CV] C=10, max_iter=200, tol=0.005 ...................................
[CV] ....... C=10, max_iter=200, tol=0.005, score=0.825, total=   0.0s
[CV] C=10, max_iter=200, tol=0.005 ...................................
[CV] ....... C=10, max_iter=200, tol=0.005, score=0.804, total=   0.0s
[CV] C=10, max_iter=200, tol=0.005 ...................................
[CV] ....... C=10, max_iter=200, tol=0.005, score=0.775, total=   0.0s
[CV] C=10, max_iter=200, tol=0.005 ...................................
[CV] ....... C=10, max_iter=200, tol=0.005, score=0.768, total=   0.0s
[CV] C=10, max_iter=200, tol=0.005 ...................................
[CV] ....... C=10, max_iter=200, tol=0.005, score=0.831, total=   0.0s
[CV] C=10, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=300, tol=0.0001, score=0.825, total=   0.0s
[CV] C=10, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=300, tol=0.0001, score=0.804, total=   0.0s
[CV] C=10, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=300, tol=0.0001, score=0.775, total=   0.0s
[CV] C=10, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=300, tol=0.0001, score=0.768, total=   0.0s
[CV] C=10, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=10, max_iter=300, tol=0.0001, score=0.831, total=   0.0s
[CV] C=10, max_iter=300, tol=0.001 ...................................
[CV] ....... C=10, max_iter=300, tol=0.001, score=0.825, total=   0.0s
[CV] C=10, max_iter=300, tol=0.001 ...................................
[CV] ....... C=10, max_iter=300, tol=0.001, score=0.804, total=   0.0s
[CV] C=10, max_iter=300, tol=0.001 ...................................
[CV] ....... C=10, max_iter=300, tol=0.001, score=0.775, total=   0.0s
[CV] C=10, max_iter=300, tol=0.001 ...................................
[CV] ....... C=10, max_iter=300, tol=0.001, score=0.768, total=   0.0s
[CV] C=10, max_iter=300, tol=0.001 ...................................
[CV] ....... C=10, max_iter=300, tol=0.001, score=0.831, total=   0.0s
[CV] C=10, max_iter=300, tol=0.005 ...................................
[CV] ....... C=10, max_iter=300, tol=0.005, score=0.825, total=   0.0s
[CV] C=10, max_iter=300, tol=0.005 ...................................
[CV] ....... C=10, max_iter=300, tol=0.005, score=0.804, total=   0.0s
[CV] C=10, max_iter=300, tol=0.005 ...................................
[CV] ....... C=10, max_iter=300, tol=0.005, score=0.775, total=   0.0s
[CV] C=10, max_iter=300, tol=0.005 ...................................
[CV] ....... C=10, max_iter=300, tol=0.005, score=0.768, total=   0.0s
[CV] C=10, max_iter=300, tol=0.005 ...................................
[CV] ....... C=10, max_iter=300, tol=0.005, score=0.831, total=   0.0s
[CV] C=50, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=100, tol=0.0001, score=0.825, total=   0.0s
[CV] C=50, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=100, tol=0.0001, score=0.804, total=   0.0s
[CV] C=50, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=100, tol=0.0001, score=0.775, total=   0.0s
[CV] C=50, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=100, tol=0.0001, score=0.768, total=   0.0s
[CV] C=50, max_iter=100, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=100, tol=0.0001, score=0.831, total=   0.0s
[CV] C=50, max_iter=100, tol=0.001 ...................................
[CV] ....... C=50, max_iter=100, tol=0.001, score=0.825, total=   0.0s
[CV] C=50, max_iter=100, tol=0.001 ...................................
[CV] ....... C=50, max_iter=100, tol=0.001, score=0.804, total=   0.0s
[CV] C=50, max_iter=100, tol=0.001 ...................................
[CV] ....... C=50, max_iter=100, tol=0.001, score=0.775, total=   0.0s
[CV] C=50, max_iter=100, tol=0.001 ...................................
[CV] ....... C=50, max_iter=100, tol=0.001, score=0.768, total=   0.0s
[CV] C=50, max_iter=100, tol=0.001 ...................................
[CV] ....... C=50, max_iter=100, tol=0.001, score=0.831, total=   0.0s
[CV] C=50, max_iter=100, tol=0.005 ...................................
[CV] ....... C=50, max_iter=100, tol=0.005, score=0.825, total=   0.0s
[CV] C=50, max_iter=100, tol=0.005 ...................................
[CV] ....... C=50, max_iter=100, tol=0.005, score=0.804, total=   0.0s
[CV] C=50, max_iter=100, tol=0.005 ...................................
[CV] ....... C=50, max_iter=100, tol=0.005, score=0.775, total=   0.0s
[CV] C=50, max_iter=100, tol=0.005 ...................................
[CV] ....... C=50, max_iter=100, tol=0.005, score=0.768, total=   0.0s
[CV] C=50, max_iter=100, tol=0.005 ...................................
[CV] ....... C=50, max_iter=100, tol=0.005, score=0.831, total=   0.0s
[CV] C=50, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=200, tol=0.0001, score=0.825, total=   0.0s
[CV] C=50, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=200, tol=0.0001, score=0.804, total=   0.0s
[CV] C=50, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=200, tol=0.0001, score=0.775, total=   0.0s
[CV] C=50, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=200, tol=0.0001, score=0.768, total=   0.0s
[CV] C=50, max_iter=200, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=200, tol=0.0001, score=0.831, total=   0.0s
[CV] C=50, max_iter=200, tol=0.001 ...................................
[CV] ....... C=50, max_iter=200, tol=0.001, score=0.825, total=   0.0s

C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

[CV] C=50, max_iter=200, tol=0.001 ...................................
[CV] ....... C=50, max_iter=200, tol=0.001, score=0.804, total=   0.0s
[CV] C=50, max_iter=200, tol=0.001 ...................................
[CV] ....... C=50, max_iter=200, tol=0.001, score=0.775, total=   0.0s
[CV] C=50, max_iter=200, tol=0.001 ...................................
[CV] ....... C=50, max_iter=200, tol=0.001, score=0.768, total=   0.0s
[CV] C=50, max_iter=200, tol=0.001 ...................................
[CV] ....... C=50, max_iter=200, tol=0.001, score=0.831, total=   0.0s
[CV] C=50, max_iter=200, tol=0.005 ...................................
[CV] ....... C=50, max_iter=200, tol=0.005, score=0.825, total=   0.0s
[CV] C=50, max_iter=200, tol=0.005 ...................................
[CV] ....... C=50, max_iter=200, tol=0.005, score=0.804, total=   0.0s
[CV] C=50, max_iter=200, tol=0.005 ...................................
[CV] ....... C=50, max_iter=200, tol=0.005, score=0.775, total=   0.0s
[CV] C=50, max_iter=200, tol=0.005 ...................................
[CV] ....... C=50, max_iter=200, tol=0.005, score=0.768, total=   0.0s
[CV] C=50, max_iter=200, tol=0.005 ...................................
[CV] ....... C=50, max_iter=200, tol=0.005, score=0.831, total=   0.0s
[CV] C=50, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=300, tol=0.0001, score=0.825, total=   0.0s
[CV] C=50, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=300, tol=0.0001, score=0.804, total=   0.0s
[CV] C=50, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=300, tol=0.0001, score=0.775, total=   0.0s
[CV] C=50, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=300, tol=0.0001, score=0.768, total=   0.0s
[CV] C=50, max_iter=300, tol=0.0001 ..................................
[CV] ...... C=50, max_iter=300, tol=0.0001, score=0.831, total=   0.0s
[CV] C=50, max_iter=300, tol=0.001 ...................................
[CV] ....... C=50, max_iter=300, tol=0.001, score=0.825, total=   0.0s
[CV] C=50, max_iter=300, tol=0.001 ...................................
[CV] ....... C=50, max_iter=300, tol=0.001, score=0.804, total=   0.0s
[CV] C=50, max_iter=300, tol=0.001 ...................................
[CV] ....... C=50, max_iter=300, tol=0.001, score=0.775, total=   0.0s
[CV] C=50, max_iter=300, tol=0.001 ...................................
[CV] ....... C=50, max_iter=300, tol=0.001, score=0.768, total=   0.0s
[CV] C=50, max_iter=300, tol=0.001 ...................................
[CV] ....... C=50, max_iter=300, tol=0.001, score=0.831, total=   0.0s
[CV] C=50, max_iter=300, tol=0.005 ...................................
[CV] ....... C=50, max_iter=300, tol=0.005, score=0.825, total=   0.0s
[CV] C=50, max_iter=300, tol=0.005 ...................................
[CV] ....... C=50, max_iter=300, tol=0.005, score=0.804, total=   0.0s
[CV] C=50, max_iter=300, tol=0.005 ...................................
[CV] ....... C=50, max_iter=300, tol=0.005, score=0.775, total=   0.0s
[CV] C=50, max_iter=300, tol=0.005 ...................................
[CV] ....... C=50, max_iter=300, tol=0.005, score=0.768, total=   0.0s
[CV] C=50, max_iter=300, tol=0.005 ...................................
[CV] ....... C=50, max_iter=300, tol=0.005, score=0.831, total=   0.0s
[CV] C=100, max_iter=100, tol=0.0001 .................................
[CV] ..... C=100, max_iter=100, tol=0.0001, score=0.825, total=   0.0s

C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

[CV] C=100, max_iter=100, tol=0.0001 .................................
[CV] ..... C=100, max_iter=100, tol=0.0001, score=0.804, total=   0.0s
[CV] C=100, max_iter=100, tol=0.0001 .................................
[CV] ..... C=100, max_iter=100, tol=0.0001, score=0.775, total=   0.0s
[CV] C=100, max_iter=100, tol=0.0001 .................................
[CV] ..... C=100, max_iter=100, tol=0.0001, score=0.768, total=   0.0s
[CV] C=100, max_iter=100, tol=0.0001 .................................
[CV] ..... C=100, max_iter=100, tol=0.0001, score=0.831, total=   0.0s
[CV] C=100, max_iter=100, tol=0.001 ..................................
[CV] ...... C=100, max_iter=100, tol=0.001, score=0.825, total=   0.0s
[CV] C=100, max_iter=100, tol=0.001 ..................................
[CV] ...... C=100, max_iter=100, tol=0.001, score=0.804, total=   0.0s
[CV] C=100, max_iter=100, tol=0.001 ..................................
[CV] ...... C=100, max_iter=100, tol=0.001, score=0.775, total=   0.0s
[CV] C=100, max_iter=100, tol=0.001 ..................................
[CV] ...... C=100, max_iter=100, tol=0.001, score=0.768, total=   0.0s
[CV] C=100, max_iter=100, tol=0.001 ..................................
[CV] ...... C=100, max_iter=100, tol=0.001, score=0.831, total=   0.0s
[CV] C=100, max_iter=100, tol=0.005 ..................................
[CV] ...... C=100, max_iter=100, tol=0.005, score=0.825, total=   0.0s
[CV] C=100, max_iter=100, tol=0.005 ..................................
[CV] ...... C=100, max_iter=100, tol=0.005, score=0.804, total=   0.0s
[CV] C=100, max_iter=100, tol=0.005 ..................................
[CV] ...... C=100, max_iter=100, tol=0.005, score=0.775, total=   0.0s
[CV] C=100, max_iter=100, tol=0.005 ..................................
[CV] ...... C=100, max_iter=100, tol=0.005, score=0.768, total=   0.0s
[CV] C=100, max_iter=100, tol=0.005 ..................................
[CV] ...... C=100, max_iter=100, tol=0.005, score=0.831, total=   0.0s
[CV] C=100, max_iter=200, tol=0.0001 .................................
[CV] ..... C=100, max_iter=200, tol=0.0001, score=0.825, total=   0.0s
[CV] C=100, max_iter=200, tol=0.0001 .................................
[CV] ..... C=100, max_iter=200, tol=0.0001, score=0.804, total=   0.0s
[CV] C=100, max_iter=200, tol=0.0001 .................................
[CV] ..... C=100, max_iter=200, tol=0.0001, score=0.775, total=   0.0s
[CV] C=100, max_iter=200, tol=0.0001 .................................
[CV] ..... C=100, max_iter=200, tol=0.0001, score=0.768, total=   0.0s
[CV] C=100, max_iter=200, tol=0.0001 .................................
[CV] ..... C=100, max_iter=200, tol=0.0001, score=0.831, total=   0.0s
[CV] C=100, max_iter=200, tol=0.001 ..................................
[CV] ...... C=100, max_iter=200, tol=0.001, score=0.825, total=   0.0s
[CV] C=100, max_iter=200, tol=0.001 ..................................
[CV] ...... C=100, max_iter=200, tol=0.001, score=0.804, total=   0.0s
[CV] C=100, max_iter=200, tol=0.001 ..................................
[CV] ...... C=100, max_iter=200, tol=0.001, score=0.775, total=   0.0s
[CV] C=100, max_iter=200, tol=0.001 ..................................
[CV] ...... C=100, max_iter=200, tol=0.001, score=0.768, total=   0.0s
[CV] C=100, max_iter=200, tol=0.001 ..................................
[CV] ...... C=100, max_iter=200, tol=0.001, score=0.831, total=   0.0s
[CV] C=100, max_iter=200, tol=0.005 ..................................
[CV] ...... C=100, max_iter=200, tol=0.005, score=0.825, total=   0.0s
[CV] C=100, max_iter=200, tol=0.005 ..................................
[CV] ...... C=100, max_iter=200, tol=0.005, score=0.804, total=   0.0s
[CV] C=100, max_iter=200, tol=0.005 ..................................
[CV] ...... C=100, max_iter=200, tol=0.005, score=0.775, total=   0.0s
[CV] C=100, max_iter=200, tol=0.005 ..................................
[CV] ...... C=100, max_iter=200, tol=0.005, score=0.768, total=   0.0s
[CV] C=100, max_iter=200, tol=0.005 ..................................
[CV] ...... C=100, max_iter=200, tol=0.005, score=0.831, total=   0.0s
[CV] C=100, max_iter=300, tol=0.0001 .................................
[CV] ..... C=100, max_iter=300, tol=0.0001, score=0.825, total=   0.0s
[CV] C=100, max_iter=300, tol=0.0001 .................................

C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

[CV] ..... C=100, max_iter=300, tol=0.0001, score=0.804, total=   0.0s
[CV] C=100, max_iter=300, tol=0.0001 .................................
[CV] ..... C=100, max_iter=300, tol=0.0001, score=0.775, total=   0.0s
[CV] C=100, max_iter=300, tol=0.0001 .................................
[CV] ..... C=100, max_iter=300, tol=0.0001, score=0.768, total=   0.0s
[CV] C=100, max_iter=300, tol=0.0001 .................................
[CV] ..... C=100, max_iter=300, tol=0.0001, score=0.831, total=   0.0s
[CV] C=100, max_iter=300, tol=0.001 ..................................
[CV] ...... C=100, max_iter=300, tol=0.001, score=0.825, total=   0.0s
[CV] C=100, max_iter=300, tol=0.001 ..................................
[CV] ...... C=100, max_iter=300, tol=0.001, score=0.804, total=   0.0s
[CV] C=100, max_iter=300, tol=0.001 ..................................
[CV] ...... C=100, max_iter=300, tol=0.001, score=0.775, total=   0.0s
[CV] C=100, max_iter=300, tol=0.001 ..................................
[CV] ...... C=100, max_iter=300, tol=0.001, score=0.768, total=   0.0s
[CV] C=100, max_iter=300, tol=0.001 ..................................
[CV] ...... C=100, max_iter=300, tol=0.001, score=0.831, total=   0.0s
[CV] C=100, max_iter=300, tol=0.005 ..................................
[CV] ...... C=100, max_iter=300, tol=0.005, score=0.825, total=   0.0s
[CV] C=100, max_iter=300, tol=0.005 ..................................
[CV] ...... C=100, max_iter=300, tol=0.005, score=0.804, total=   0.0s
[CV] C=100, max_iter=300, tol=0.005 ..................................
[CV] ...... C=100, max_iter=300, tol=0.005, score=0.775, total=   0.0s
[CV] C=100, max_iter=300, tol=0.005 ..................................
[CV] ...... C=100, max_iter=300, tol=0.005, score=0.768, total=   0.0s
[CV] C=100, max_iter=300, tol=0.005 ..................................
[CV] ...... C=100, max_iter=300, tol=0.005, score=0.831, total=   0.0s
[CV] C=200, max_iter=100, tol=0.0001 .................................
[CV] ..... C=200, max_iter=100, tol=0.0001, score=0.825, total=   0.0s
[CV] C=200, max_iter=100, tol=0.0001 .................................
[CV] ..... C=200, max_iter=100, tol=0.0001, score=0.804, total=   0.0s
[CV] C=200, max_iter=100, tol=0.0001 .................................
[CV] ..... C=200, max_iter=100, tol=0.0001, score=0.775, total=   0.0s
[CV] C=200, max_iter=100, tol=0.0001 .................................
[CV] ..... C=200, max_iter=100, tol=0.0001, score=0.768, total=   0.0s
[CV] C=200, max_iter=100, tol=0.0001 .................................
[CV] ..... C=200, max_iter=100, tol=0.0001, score=0.831, total=   0.0s
[CV] C=200, max_iter=100, tol=0.001 ..................................
[CV] ...... C=200, max_iter=100, tol=0.001, score=0.825, total=   0.0s
[CV] C=200, max_iter=100, tol=0.001 ..................................
[CV] ...... C=200, max_iter=100, tol=0.001, score=0.804, total=   0.0s
[CV] C=200, max_iter=100, tol=0.001 ..................................
[CV] ...... C=200, max_iter=100, tol=0.001, score=0.775, total=   0.0s
[CV] C=200, max_iter=100, tol=0.001 ..................................
[CV] ...... C=200, max_iter=100, tol=0.001, score=0.768, total=   0.0s
[CV] C=200, max_iter=100, tol=0.001 ..................................
[CV] ...... C=200, max_iter=100, tol=0.001, score=0.831, total=   0.0s
[CV] C=200, max_iter=100, tol=0.005 ..................................
[CV] ...... C=200, max_iter=100, tol=0.005, score=0.825, total=   0.0s
[CV] C=200, max_iter=100, tol=0.005 ..................................
[CV] ...... C=200, max_iter=100, tol=0.005, score=0.804, total=   0.0s
[CV] C=200, max_iter=100, tol=0.005 ..................................
[CV] ...... C=200, max_iter=100, tol=0.005, score=0.775, total=   0.0s
[CV] C=200, max_iter=100, tol=0.005 ..................................
[CV] ...... C=200, max_iter=100, tol=0.005, score=0.768, total=   0.0s
[CV] C=200, max_iter=100, tol=0.005 ..................................
[CV] ...... C=200, max_iter=100, tol=0.005, score=0.831, total=   0.0s
[CV] C=200, max_iter=200, tol=0.0001 .................................
[CV] ..... C=200, max_iter=200, tol=0.0001, score=0.825, total=   0.0s
[CV] C=200, max_iter=200, tol=0.0001 .................................
[CV] ..... C=200, max_iter=200, tol=0.0001, score=0.804, total=   0.0s
[CV] C=200, max_iter=200, tol=0.0001 .................................
[CV] ..... C=200, max_iter=200, tol=0.0001, score=0.775, total=   0.0s
[CV] C=200, max_iter=200, tol=0.0001 .................................
[CV] ..... C=200, max_iter=200, tol=0.0001, score=0.768, total=   0.0s
[CV] C=200, max_iter=200, tol=0.0001 .................................
[CV] ..... C=200, max_iter=200, tol=0.0001, score=0.831, total=   0.0s
[CV] C=200, max_iter=200, tol=0.001 ..................................
[CV] ...... C=200, max_iter=200, tol=0.001, score=0.825, total=   0.0s
[CV] C=200, max_iter=200, tol=0.001 ..................................
[CV] ...... C=200, max_iter=200, tol=0.001, score=0.804, total=   0.0s
[CV] C=200, max_iter=200, tol=0.001 ..................................

C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

[CV] ...... C=200, max_iter=200, tol=0.001, score=0.775, total=   0.0s
[CV] C=200, max_iter=200, tol=0.001 ..................................
[CV] ...... C=200, max_iter=200, tol=0.001, score=0.768, total=   0.0s
[CV] C=200, max_iter=200, tol=0.001 ..................................
[CV] ...... C=200, max_iter=200, tol=0.001, score=0.831, total=   0.0s
[CV] C=200, max_iter=200, tol=0.005 ..................................
[CV] ...... C=200, max_iter=200, tol=0.005, score=0.825, total=   0.0s
[CV] C=200, max_iter=200, tol=0.005 ..................................
[CV] ...... C=200, max_iter=200, tol=0.005, score=0.804, total=   0.0s
[CV] C=200, max_iter=200, tol=0.005 ..................................
[CV] ...... C=200, max_iter=200, tol=0.005, score=0.775, total=   0.0s
[CV] C=200, max_iter=200, tol=0.005 ..................................
[CV] ...... C=200, max_iter=200, tol=0.005, score=0.768, total=   0.0s
[CV] C=200, max_iter=200, tol=0.005 ..................................
[CV] ...... C=200, max_iter=200, tol=0.005, score=0.831, total=   0.0s
[CV] C=200, max_iter=300, tol=0.0001 .................................
[CV] ..... C=200, max_iter=300, tol=0.0001, score=0.825, total=   0.0s
[CV] C=200, max_iter=300, tol=0.0001 .................................
[CV] ..... C=200, max_iter=300, tol=0.0001, score=0.804, total=   0.0s
[CV] C=200, max_iter=300, tol=0.0001 .................................
[CV] ..... C=200, max_iter=300, tol=0.0001, score=0.775, total=   0.0s
[CV] C=200, max_iter=300, tol=0.0001 .................................
[CV] ..... C=200, max_iter=300, tol=0.0001, score=0.768, total=   0.0s
[CV] C=200, max_iter=300, tol=0.0001 .................................
[CV] ..... C=200, max_iter=300, tol=0.0001, score=0.831, total=   0.0s
[CV] C=200, max_iter=300, tol=0.001 ..................................
[CV] ...... C=200, max_iter=300, tol=0.001, score=0.825, total=   0.0s
[CV] C=200, max_iter=300, tol=0.001 ..................................
[CV] ...... C=200, max_iter=300, tol=0.001, score=0.804, total=   0.0s
[CV] C=200, max_iter=300, tol=0.001 ..................................
[CV] ...... C=200, max_iter=300, tol=0.001, score=0.775, total=   0.0s
[CV] C=200, max_iter=300, tol=0.001 ..................................
[CV] ...... C=200, max_iter=300, tol=0.001, score=0.768, total=   0.0s
[CV] C=200, max_iter=300, tol=0.001 ..................................
[CV] ...... C=200, max_iter=300, tol=0.001, score=0.831, total=   0.0s
[CV] C=200, max_iter=300, tol=0.005 ..................................
[CV] ...... C=200, max_iter=300, tol=0.005, score=0.825, total=   0.0s
[CV] C=200, max_iter=300, tol=0.005 ..................................
[CV] ...... C=200, max_iter=300, tol=0.005, score=0.804, total=   0.0s
[CV] C=200, max_iter=300, tol=0.005 ..................................
[CV] ...... C=200, max_iter=300, tol=0.005, score=0.775, total=   0.0s
[CV] C=200, max_iter=300, tol=0.005 ..................................
[CV] ...... C=200, max_iter=300, tol=0.005, score=0.768, total=   0.0s
[CV] C=200, max_iter=300, tol=0.005 ..................................
[CV] ...... C=200, max_iter=300, tol=0.005, score=0.831, total=   0.0s
[CV] C=500, max_iter=100, tol=0.0001 .................................
[CV] ..... C=500, max_iter=100, tol=0.0001, score=0.825, total=   0.0s
[CV] C=500, max_iter=100, tol=0.0001 .................................
[CV] ..... C=500, max_iter=100, tol=0.0001, score=0.804, total=   0.0s
[CV] C=500, max_iter=100, tol=0.0001 .................................
[CV] ..... C=500, max_iter=100, tol=0.0001, score=0.775, total=   0.0s
[CV] C=500, max_iter=100, tol=0.0001 .................................
[CV] ..... C=500, max_iter=100, tol=0.0001, score=0.768, total=   0.0s
[CV] C=500, max_iter=100, tol=0.0001 .................................
[CV] ..... C=500, max_iter=100, tol=0.0001, score=0.831, total=   0.0s
[CV] C=500, max_iter=100, tol=0.001 ..................................
[CV] ...... C=500, max_iter=100, tol=0.001, score=0.825, total=   0.0s
[CV] C=500, max_iter=100, tol=0.001 ..................................
[CV] ...... C=500, max_iter=100, tol=0.001, score=0.804, total=   0.0s
[CV] C=500, max_iter=100, tol=0.001 ..................................
[CV] ...... C=500, max_iter=100, tol=0.001, score=0.775, total=   0.0s
[CV] C=500, max_iter=100, tol=0.001 ..................................
[CV] ...... C=500, max_iter=100, tol=0.001, score=0.768, total=   0.0s
[CV] C=500, max_iter=100, tol=0.001 ..................................
[CV] ...... C=500, max_iter=100, tol=0.001, score=0.831, total=   0.0s
[CV] C=500, max_iter=100, tol=0.005 ..................................
[CV] ...... C=500, max_iter=100, tol=0.005, score=0.825, total=   0.0s
[CV] C=500, max_iter=100, tol=0.005 ..................................
[CV] ...... C=500, max_iter=100, tol=0.005, score=0.804, total=   0.0s
[CV] C=500, max_iter=100, tol=0.005 ..................................
[CV] ...... C=500, max_iter=100, tol=0.005, score=0.775, total=   0.0s
[CV] C=500, max_iter=100, tol=0.005 ..................................
[CV] ...... C=500, max_iter=100, tol=0.005, score=0.768, total=   0.0s
[CV] C=500, max_iter=100, tol=0.005 ..................................
[CV] ...... C=500, max_iter=100, tol=0.005, score=0.831, total=   0.0s
[CV] C=500, max_iter=200, tol=0.0001 .................................
[CV] ..... C=500, max_iter=200, tol=0.0001, score=0.825, total=   0.0s
[CV] C=500, max_iter=200, tol=0.0001 .................................
[CV] ..... C=500, max_iter=200, tol=0.0001, score=0.804, total=   0.0s
[CV] C=500, max_iter=200, tol=0.0001 .................................
[CV] ..... C=500, max_iter=200, tol=0.0001, score=0.775, total=   0.0s

C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

[CV] C=500, max_iter=200, tol=0.0001 .................................
[CV] ..... C=500, max_iter=200, tol=0.0001, score=0.768, total=   0.0s
[CV] C=500, max_iter=200, tol=0.0001 .................................
[CV] ..... C=500, max_iter=200, tol=0.0001, score=0.831, total=   0.0s
[CV] C=500, max_iter=200, tol=0.001 ..................................
[CV] ...... C=500, max_iter=200, tol=0.001, score=0.825, total=   0.0s
[CV] C=500, max_iter=200, tol=0.001 ..................................
[CV] ...... C=500, max_iter=200, tol=0.001, score=0.804, total=   0.0s
[CV] C=500, max_iter=200, tol=0.001 ..................................
[CV] ...... C=500, max_iter=200, tol=0.001, score=0.775, total=   0.0s
[CV] C=500, max_iter=200, tol=0.001 ..................................
[CV] ...... C=500, max_iter=200, tol=0.001, score=0.768, total=   0.0s
[CV] C=500, max_iter=200, tol=0.001 ..................................
[CV] ...... C=500, max_iter=200, tol=0.001, score=0.831, total=   0.0s
[CV] C=500, max_iter=200, tol=0.005 ..................................
[CV] ...... C=500, max_iter=200, tol=0.005, score=0.825, total=   0.0s
[CV] C=500, max_iter=200, tol=0.005 ..................................
[CV] ...... C=500, max_iter=200, tol=0.005, score=0.804, total=   0.0s
[CV] C=500, max_iter=200, tol=0.005 ..................................
[CV] ...... C=500, max_iter=200, tol=0.005, score=0.775, total=   0.0s
[CV] C=500, max_iter=200, tol=0.005 ..................................
[CV] ...... C=500, max_iter=200, tol=0.005, score=0.768, total=   0.0s
[CV] C=500, max_iter=200, tol=0.005 ..................................
[CV] ...... C=500, max_iter=200, tol=0.005, score=0.831, total=   0.0s
[CV] C=500, max_iter=300, tol=0.0001 .................................
[CV] ..... C=500, max_iter=300, tol=0.0001, score=0.825, total=   0.0s
[CV] C=500, max_iter=300, tol=0.0001 .................................
[CV] ..... C=500, max_iter=300, tol=0.0001, score=0.804, total=   0.0s
[CV] C=500, max_iter=300, tol=0.0001 .................................
[CV] ..... C=500, max_iter=300, tol=0.0001, score=0.775, total=   0.0s
[CV] C=500, max_iter=300, tol=0.0001 .................................
[CV] ..... C=500, max_iter=300, tol=0.0001, score=0.768, total=   0.0s
[CV] C=500, max_iter=300, tol=0.0001 .................................
[CV] ..... C=500, max_iter=300, tol=0.0001, score=0.831, total=   0.0s
[CV] C=500, max_iter=300, tol=0.001 ..................................
[CV] ...... C=500, max_iter=300, tol=0.001, score=0.825, total=   0.0s
[CV] C=500, max_iter=300, tol=0.001 ..................................
[CV] ...... C=500, max_iter=300, tol=0.001, score=0.804, total=   0.0s
[CV] C=500, max_iter=300, tol=0.001 ..................................
[CV] ...... C=500, max_iter=300, tol=0.001, score=0.775, total=   0.0s
[CV] C=500, max_iter=300, tol=0.001 ..................................
[CV] ...... C=500, max_iter=300, tol=0.001, score=0.768, total=   0.0s
[CV] C=500, max_iter=300, tol=0.001 ..................................
[CV] ...... C=500, max_iter=300, tol=0.001, score=0.831, total=   0.0s
[CV] C=500, max_iter=300, tol=0.005 ..................................
[CV] ...... C=500, max_iter=300, tol=0.005, score=0.825, total=   0.0s
[CV] C=500, max_iter=300, tol=0.005 ..................................
[CV] ...... C=500, max_iter=300, tol=0.005, score=0.804, total=   0.0s
[CV] C=500, max_iter=300, tol=0.005 ..................................
[CV] ...... C=500, max_iter=300, tol=0.005, score=0.775, total=   0.0s
[CV] C=500, max_iter=300, tol=0.005 ..................................
[CV] ...... C=500, max_iter=300, tol=0.005, score=0.768, total=   0.0s
[CV] C=500, max_iter=300, tol=0.005 ..................................
[CV] ...... C=500, max_iter=300, tol=0.005, score=0.831, total=   0.0s

C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
[Parallel(n_jobs=1)]: Done 315 out of 315 | elapsed:    1.5s finished
C:\Users\patri\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 5, 10, 50, 100, 200, 500],
                         'max_iter': [100, 200, 300],
                         'tol': [0.0001, 0.001, 0.005]},
             verbose=3)

In [119]:
print(grid.best_params_)
print(grid.best_score_)

{'C': 10, 'max_iter': 100, 'tol': 0.0001}
0.8005220131980696

In [120]:
#compare with the test data!
predictions = grid.predict(X_test_scaled)

In [121]:
#check classification report for how the tuned model did!
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions,
                            target_names=["Actual", "Predicted"]))

              precision    recall  f1-score   support

      Actual       0.80      0.86      0.83       105
   Predicted       0.78      0.70      0.74        74

    accuracy                           0.79       179
   macro avg       0.79      0.78      0.78       179
weighted avg       0.79      0.79      0.79       179

In [122]:
y_test

     Survived
709         1
439         0
840         0
720         1
39          1
..        ...
433         0
773         0
25          1
84          1
10          1

[179 rows x 1 columns]

# Test Data Operations

In [131]:
test_df = pd.read_csv("test.csv")
test_df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [132]:
# check NAs in test data

test_df.drop(["Cabin", "Ticket", "PassengerId"], axis=1, inplace=True)

boolean_test_df = test_df.isna()

for i in range(boolean_test_df.index.size):
    for j in range(8):
        if(boolean_test_df.iloc[i, j]):
            print("row: {} column: {} name: {}".format(i, boolean_test_df.columns[j], test_df.iloc[i, 1]))

row: 10 column: Age name: Ilieff, Mr. Ylio
row: 22 column: Age name: Flegenheim, Mrs. Alfred (Antoinette)
row: 29 column: Age name: Samaan, Mr. Elias
row: 33 column: Age name: Johnston, Mrs. Andrew G (Elizabeth Lily" Watson)"
row: 36 column: Age name: Roth, Miss. Sarah A
row: 39 column: Age name: Hee, Mr. Ling
row: 41 column: Age name: Franklin, Mr. Thomas Parham
row: 47 column: Age name: Shaughnessy, Mr. Patrick
row: 54 column: Age name: Mangiavacchi, Mr. Serafino Emilio
row: 58 column: Age name: Davison, Mr. Thomas Henry
row: 65 column: Age name: Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)
row: 76 column: Age name: Miles, Mr. Frank
row: 83 column: Age name: Demetri, Mr. Marinko
row: 84 column: Age name: Lamb, Mr. John Joseph
row: 85 column: Age name: Khalil, Mr. Betros
row: 88 column: Age name: O'Donoghue, Ms. Bridget
row: 91 column: Age name: Pedersen, Mr. Olaf
row: 93 column: Age name: Guest, Mr. Robert
row: 102 column: Age name: Foley, Mr. William
row: 107 column: Age name: Ryan, Mr. Edward
row: 108 column: Age name: Willer, Mr. Aaron (Abi Weller")"
row: 111 column: Age name: Shine, Miss. Ellen Natalia
row: 116 column: Age name: Thomas, Mr. John
row: 121 column: Age name: Kiernan, Mr. John
row: 124 column: Age name: Kennedy, Mr. John
row: 127 column: Age name: McCoy, Miss. Alicia
row: 132 column: Age name: Lefebre, Mrs. Frank (Frances)
row: 133 column: Age name: Thomas, Mr. Charles P
row: 146 column: Age name: Hilliard, Mr. Herbert Henry
row: 148 column: Age name: Crafton, Mr. John Bertram
row: 151 column: Age name: Matinoff, Mr. Nicola
row: 152 column: Fare name: Storey, Mr. Thomas
row: 160 column: Age name: Smyth, Miss. Julia
row: 163 column: Age name: Pearce, Mr. Ernest
row: 168 column: Age name: Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genevieve Fosdick)
row: 170 column: Age name: Lithman, Mr. Simon
row: 173 column: Age name: Torfa, Mr. Assad
row: 183 column: Age name: Lane, Mr. Patrick
row: 188 column: Age name: Sage, Miss. Ada
row: 191 column: Age name: Salomon, Mr. Abraham L
row: 199 column: Age name: Rasmussen, Mrs. (Lena Jacobsen Solvang)
row: 200 column: Age name: Murphy, Miss. Nora
row: 205 column: Age name: Omont, Mr. Alfred Fernand
row: 211 column: Age name: Finoli, Mr. Luigi
row: 216 column: Age name: Mahon, Miss. Bridget Delia
row: 219 column: Age name: Thomson, Mr. Alexander Morrison
row: 225 column: Age name: Moubarek, Mrs. George (Omine Amenia" Alexander)"
row: 227 column: Age name: McNeill, Miss. Bridget
row: 233 column: Age name: Linehan, Mr. Michael
row: 243 column: Age name: Hyman, Mr. Abraham
row: 244 column: Age name: Johnston, Master. William Arthur Willie""
row: 249 column: Age name: Khalil, Mrs. Betros (Zahie Maria" Elias)"
row: 255 column: Age name: MacKay, Mr. George William
row: 256 column: Age name: Mahon, Mr. John
row: 265 column: Age name: Lyntakoff, Mr. Stanko
row: 266 column: Age name: Chisholm, Mr. Roderick Robert Crispin
row: 267 column: Age name: Warren, Mr. Charles William
row: 268 column: Age name: Howard, Miss. May Elizabeth
row: 271 column: Age name: Fox, Mr. Patrick
row: 273 column: Age name: Lennon, Miss. Mary
row: 274 column: Age name: Saade, Mr. Jean Nassr
row: 282 column: Age name: Fleming, Miss. Honora
row: 286 column: Age name: Franklin, Mr. Charles (Charles Fardon)
row: 288 column: Age name: Mardirosian, Mr. Sarkis
row: 289 column: Age name: Ford, Mr. Arthur
row: 290 column: Age name: Rheims, Mr. George Alexander Lucien
row: 292 column: Age name: Nasr, Mr. Mustafa
row: 297 column: Age name: Samaan, Mr. Hanna
row: 301 column: Age name: Malachard, Mr. Noel
row: 304 column: Age name: McCarthy, Miss. Catherine Katie""
row: 312 column: Age name: Sadowitz, Mr. Harry
row: 332 column: Age name: Thomas, Mr. Tannous
row: 339 column: Age name: Betros, Master. Seman
row: 342 column: Age name: Sage, Mr. John George
row: 344 column: Age name: van Billiard, Master. James William
row: 357 column: Age name: Lockyer, Mr. Edward
row: 358 column: Age name: O'Keefe, Mr. Patrick
row: 365 column: Age name: Sage, Mrs. John (Annie Bullen)
row: 366 column: Age name: Caram, Mr. Joseph
row: 380 column: Age name: O'Connor, Mr. Patrick
row: 382 column: Age name: Risien, Mrs. Samuel (Emma)
row: 384 column: Age name: Wheeler, Mr. Edwin Frederick""
row: 408 column: Age name: Riordan, Miss. Johanna Hannah""
row: 410 column: Age name: Naughton, Miss. Hannah
row: 413 column: Age name: Spector, Mr. Woolf
row: 416 column: Age name: Ware, Mr. Frederick
row: 417 column: Age name: Peter, Master. Michael J

In [133]:
#ignore age for first pass - later set avg. ages for children and adults based on their names (Master/Miss -> children, Mr/Mrs -> adults)
#set average fare for "Storey, Mr. Thomas" based on ticket class and embark location

In [134]:
# predict outcomes based on test data
test_df.drop(["Age", "Embarked", "Name", "Fare"], axis=1, inplace=True)

# convert non-numeric data to numbers
test_df["Sex"] = test_df["Sex"].apply(lambda x: 0 if(x=="male") else 1)
test_df

     Pclass  Sex  SibSp  Parch
0         3    0      0      0
1         3    1      1      0
2         2    0      0      0
3         3    0      0      0
4         3    1      1      1
..      ...  ...    ...    ...
413       3    0      0      0
414       1    1      0      0
415       3    0      0      0
416       3    0      0      0
417       3    0      1      1

[418 rows x 4 columns]

In [135]:
X_final_scaled = X_scaler.transform(test_df)
X_final_scaled

array([[1.        , 0.        , 0.        , 0.        ],
       [1.        , 1.        , 0.125     , 0.        ],
       [0.5       , 0.        , 0.        , 0.        ],
       ...,
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.125     , 0.16666667]])

In [136]:
#get final predictions
final_predictions = grid.predict(X_final_scaled)
final_predictions

array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0],
      dtype=int64)

In [141]:
#setup dataframe for output
output_df = pd.read_csv("test.csv")
output_df["Survived"] = final_predictions
output_df = output_df[["PassengerId", "Survived"]]
output_df

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [142]:
output_df.to_csv("logistic_classification_prediction.csv", index=False)

## Control Submission (Gender)

In [7]:
gender_only_df = pd.read_csv("gender_submission.csv")
gender_only_df

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

* Results from the gender submission provided as data give a score of about 0.76555, so any score above that is an improvement!